version: "3.7"
services:
  web1:
    build: ./quote_gen
    # container_name: gen
    ports:
      - "4999-5000:5000"
    deploy:
      replicas: 2
    volumes:
      - ./quote_gen:/app
  web2:
    build: ./quote_disp
    # container_name: disp
    ports:
      - "5001-5002:5001"
    deploy:
      replicas: 2
    volumes:
      - ./quote_disp:/app
    depends_on:
      - web1